packages:
  - "."

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustLockfile: false

trustPolicyExclude:
  - "tailwind-merge@2.6.1"
  - "ua-parser-js@1.0.41"

allowBuilds:
  "@clerk/shared": true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  sharp: true
